version: '3.8'

services:
  productcatalog:
    build:
      context: .
      dockerfile: ProductCatalog/Dockerfile
    container_name: productcatalog
    ports:
      - "5001:80"
    networks:
      - mynetwork

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: apigateway
    ports:
      - "5000:80"
    networks:
      - mynetwork
    depends_on:
      - productcatalog

  configserver:
    build:
      context: .
      dockerfile: ConfigServer/Dockerfile
    container_name: configserver
    ports:
      - "8888:8888"
    networks:
      - mynetwork

  discoveryserver:
    build:
      context: .
      dockerfile: DiscoveryServer/Dockerfile
    container_name: discoveryserver
    ports:
      - "8761:8761"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
